Benchling-Open-Source/allotropy

- CHANGELOG.md
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_parser_test.py
- Redefine AppBio Quantstudio get_model test to take into account calculated document references
> test: redefine AppBio Quantstudio get_model test to take into account calculated document references

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_builders.py
- Ignore unexpected sections in AppBio Quantstudio input file
- Accept comma as thousand indicator in AppBio Quantstudio results section
> fix: handle unexpected section and comma as thousand separator in Appbio Quantstudio

- src/allotropy/allotrope/schemas/pcr/BENCHLING/2023/09/dpcr.json
removed data processing document as being required for processed data document
updated 'reference sample description' to 'reference DNA copy number setting' within the data processing document for the calculated data document.
> chore: Corrected dPCR json schema

- pyproject.toml
- src/allotropy/allotrope/schema_parser/generate_schemas.py
Needed because 1.6.0 released yesterday, GitHub started checking against it, and there's a suppression that needs to change for mypy to keep passing.
> Update to mypy 1.6.0

- pyproject.toml
"Fix" may be more self-evidently named, but better to stick with Hatch default command keyword, especially given that all other `lint` commands use the default keywords.
Note that CI checks run `hatch run lint:all`, which does not run `fmt` but `style`.
> Rename 'fix' to 'fmt' to match Hatch default

- CHANGELOG.md
- src/allotropy/parsers/utils/timestamp_parser.py
- tests/parsers/utils/timestamp_parser_test.py
Motivation: we see this in some instrument files we are currently handling, so we know it happens and we would like to handle it. This does not risk mis-handling correct timestamps, just increases chance we'll handle non-correct timestamps.
> fix: Allow fuzzy timestamps in timestamp parser

- CONTRIBUTING.md
Fix link to published ASM schemas in **Adding a new converter** section.
> fix: fix typo in CONTRIBUTING.md - ASM schema link.

- pyproject.toml
[Ruff has drop-in parity with flake8](https://docs.astral.sh/ruff/), and we run ruff, so don't run flake8. (It's much slower than ruff.)
> Don't run flake8

- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- src/allotropy/parsers/utils/values.py
`assert_not_none` does the same thing ... albeit with different error message defaults, but that's not enough to justify keeping `assert_df`.
> Remove assert_df

- pyproject.toml
Pin cattrs to 23.1.2, the latest version released before today. Updating to 23.2.0 should be done carefully as there are some potentially breaking changes called out in release notes:
https://catt.rs/en/latest/history.html#history
(not to mention upgrading requires at least one type suppression or code change, and checks on all open PRs are currently failing)
> Pin cattrs

- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_reader.py
Note that `Series` does not have generics in src but does in stubs, so `from __future__ import annotations` is needed:
https://stackoverflow.com/questions/75452897/adding-generic-typing-to-function-signature-with-pandas-series-results-in-type
> Add generics to vi_cell_blu_reader

- src/allotropy/allotrope/models/shared/definitions/definitions.py
Move dataclasses up, then remove a lot of whitespace and sort alphabetically.
> Improve ordering in shared/definitions/definitions

- src/allotropy/parser_factory.py
- src/allotropy/to_allotrope.py
Use `get_parser()` externally, rename to indicate members that shouldn't be used externally, and sort lines.
> Clean up ParserFactory

- src/allotropy/parsers/agilent_gen5/agilent_gen5_parser.py
- src/allotropy/parsers/agilent_gen5/section_reader.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_parser.py
- src/allotropy/parsers/lines_reader.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_parser.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_parser.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/lines_reader_test.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
Separate the concerns of:
1. Parsing an input stream into a list of strings (one per line)
2. Reading through a list of strings with the methods of LinesReader (and children)
Eliminate unnecessary fields: we only need `lines` and `current_line`.
Simplify from this:
... to this:
> Simplify LinesReader

- src/allotropy/allotrope/models/shared/definitions/units.py
- src/allotropy/allotrope/schemas/shared/definitions/units.json
Addition of SquareCentimetersPerGram to support use of `attenuation coefficient` in `spectrophotometry` schema
> Addition of SquareCentimetersPerGram to units.json

- pyproject.toml
- src/allotropy/allotrope/schema_parser/generate_schemas.py
- tests/allotrope/schema_parser/generate_schemas_test.py
Add the ability to run generate schemas script as a dry run and return the number of models changed. 
Change the test to validate that no model files are changed.
This improves test coverage and prevents the test from making changes to files.
> tests: Improve schema generation test

- CHANGELOG.md
- src/allotropy/parsers/chemometec_nucleoview/nucleoview_parser.py
- src/allotropy/parsers/chemometec_nucleoview/nucleoview_reader.py
- tests/parsers/chemometec_nucleoview/chemometec_nucleoview_parser_test.py
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example04.csv
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example04.json
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example05.csv
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example05.json
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example06.csv
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example06.json
Add support for non-numeric values in fields that are mapped to TQuantity type values.
> Chemometic Nucleoview: support for non-numeric values

- CHANGELOG.md
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_absorbance_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example04.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_luminescence_example01.json
In the Perkin Elmer Envision Adapter the calculated data name of the calculated data documents was being incorrectly parsed.
- Instead of grabbing the left part of the `formula` column on the `Plate information` block, the adapter was taking the right part.
- Added additional test for the structure class in charge of parsing this property.
> Fix: calculated data name in elmer envision

- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
Don't pass values equal to the default parameter values, especially when that default is `None`.
> Simplify TDatacubeComponent instantiation in tests

- tests/parsers/agilent_gen5/to_allotrope_test.py
- tests/parsers/test_utils.py
Mostly making it possible to override `identifiers_to_exclude` in `validate_contents`. Plus some renames, not overwriting input dicts, etc.
Out of scope: making the default for `identifiers_to_exclude` be an empty list. That will require changing callers.
> Improve test_utils

- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_parser.py
- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_parser.py
Create enums to link strings and their respective dataclass types. Avoids duplicating hardcoded strings and dealing with missing-key issues in a map.
> Create SampleProperty in vi_cell_*_parser

- pyproject.toml
pandas-stubs released a 2.2.x version two days ago:
https://pypi.org/project/pandas-stubs/#history
It broke mypy. Pin to prior version to unblock development.
> Pin pandas-stubs

- tests/parsers/test_utils.py
There are no existing instances of `(int, np.int64)` mismatches, so tighten checks.
We can remove `(float, np.float64)` as well, but that will require a src change in `vi_cell_blu_parser`, so we'll do that separately.
> Make _assert_allotrope_dicts_equal() stricter

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example07.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example08.json
- Add missing ct mean calculated data documents to relative std curve experiments in AppBio Quantstudio
> fix: add missing ct mean calc docs to relative std curve in AppBio Quantstudio

- .gitignore
Ignore so PyCharm users don't accidentally commit.
Chat sessions started persisting as of the version released 2024-03-04:
https://plugins.jetbrains.com/plugin/17718-github-copilot/versions/stable/498299
> Add .idea/copilot/chatSessions to .gitignore

- src/allotropy/testing/utils.py
This check was added to ensure that someone does not accidentally commit a test with `write_actual_to_expected_on_fail`.
While that makes sense, it makes this function very frustrating/confusing to use in the middle of a unit test, as you have to set/unset the value and can't share the flag's use in other functions.
> fix: Remove assert in validate_contents

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_data_creator.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example04.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example07.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_multiple_cal_doc_wells.json
- remove inner calculated data documents from AppBio Quantstudio
This change requires the refactor of the PCR CSV converter. This task is already being developed.
> remove inner calculated data documents from AppBio Quantstudio

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example07.json
add cache to calculated data constructors in AppBio Quantstudio
This functions are design to generate a CalculatedData object each time they are called if the data they represent is available.
The CalculatedData object contains an uuid.
So, assuming the corresponding data is available, if the function is invoked two times with the same parameters, two CalculatedData objects will be created and their only difference would be the uuid.
With the cache decorator there would not be duplicated CalculatedData objects.
This PR modifies the tests because it removes the duplicated calculated documents that were present because of the previous absence of cache in these functions.
> add cache to calculated data constructors in AppBio Quantstudio

- README.md
Added missing parsers to READ.ME
- QuantStudio Design & Analysis
- PharmSpec
- Kaleido
> chore: Update README.md with missing parsers

- src/allotropy/parsers/agilent_gen5_image/agilent_gen5_image_parser.py
- src/allotropy/parsers/agilent_gen5_image/constants.py
- tests/parsers/agilent_gen5_image/testdata/96-Well Trevigen CometAssayCometChip Imaging and Analysis Sample File 23Nov15.json
- tests/parsers/agilent_gen5_image/testdata/Cell_Count_DAPI_GFP.json
- tests/parsers/agilent_gen5_image/testdata/HeLa 96well Colony 11pt Doxorubicin UprBF_TAB.json
Use optical-imaging as default device type on gen5-image adapter
> fix: use optical-imaging as default device type on gen5-image adapter

- README.md
Add `CTL ImmunoSpot` and `Agilent Gen5 Image` to list of available adapters
> chore: add CTL ImmunoSpot and Gen5 image to available adapters

- CHANGELOG.md
- src/allotropy/allotrope/schema_parser/schema_cleaner.py
- tests/allotrope/schema_parser/schema_cleaner_test.py
1. Decode UTF-8 encoded values in schema reference URLs
2. Handle empty (metadata only) object schemas when combining schemas
> fix: Fix two uncovered cases in schema cleaner

- CHANGELOG.md
- src/allotropy/allotrope/converter.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_parser.py
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_checksum_correct.json
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_simple_correct.json
`CustomInformationDocument` allows us to attach extra information that is not currently represented in the ASM schema.
The converter library already has a utility for serializing `CustomInformationDocument`, but there was no utility for adding a one to a model.
This PR adds that function, along with an example usage in `ExampleWeylandYutaniParser`.
> feat: Add library function to allow adding a CustomInformationDocument to an ASM model

- CHANGELOG.md
- src/allotropy/allotrope/converter.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_parser.py
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_checksum_correct.json
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_simple_correct.json
The first addition allowed adding a dictionary of extra information as a custom information document.
This change allows adding a custom dataclass as a custom information document, making for cleaner code.
Also fixes a bug in the original where dict key names were having underscores removed.
> feat: Add ability to add custom dataclasses as custom information document

- src/allotropy/testing/utils.py
- tests/parsers/biorad_bioplex_manager/biorad_bioplex_manager_parser_test.py
- tests/parsers/methodical_mind/methodical_mind_parser_test.py
This PR makes a couple upgrades to test_util:
- Allow writing a missing test file if `write_actual_to_expected_on_fail=True`. The standard way we add new test cases it to turn on `write_actual_to_expected_on_fail` and run to generate the test output. But, before you had to make a dummy file or the test util would fail due to the missing file. Fix that.
- Improve test util error messages:
- When overwriting file, write a helpful message
- Use DeepDiff.pretty() to write human readable messages for deepdiff
- Remove optional verbose message now that error is more readable.
> test: Allow test util to write new test output and improve error messages

- CHANGELOG.md
- src/allotropy/allotrope/converter.py
- src/allotropy/parsers/biorad_bioplex_manager/biorad_bioplex_manager_parser.py
- src/allotropy/parsers/utils/values.py
- tests/allotrope/converter_test.py
- tests/parsers/utils/values_test.py
This PR updates custom logic for omitting keys in the converter.
It is updated to *not* omit `None` keys when they are for a required field.
The PR also removes a util that was previously doing this in a special case, since it is now general behavior.
> feat: Update converter to keep None values for required fields and remove redundant util

- src/allotropy/parsers/agilent_gen5_image/agilent_gen5_image_parser.py
- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_parser.py
- src/allotropy/parsers/chemometec_nucleoview/nucleoview_parser.py
- src/allotropy/parsers/chemometec_nucleoview/nucleoview_reader.py
- src/allotropy/parsers/methodical_mind/methodical_mind_structure.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_parser_test.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_parser_test.py
- tests/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_structure_test.py
- tests/parsers/ctl_immunospot/to_allotrope_test.py
- tests/parsers/mabtech_apex/mabtech_apex_to_allotrope_test.py
- tests/parsers/revvity_kaleido/to_allotrope_test.py
Reduced warnings while running unit tests from 142 -> 9
Specifically:
1. Remove per-parser pytest marks. It was agreed these weren't needed since you can filter test by directory
2. Suppress warning while reading excel files without style sheet
3. Index pandas dataframe using `iloc` (future proofing)
4. Remove use of `skipfooter` by manually dropping last line in dataframe instead (future proofing)
5. Opt-in to future behavior of not automatically downcasting in pd.replace
The remaining warnings are related to duplicated names in schema class generator script that should hopefully go away with modularized schemas :D
> chore: Clean up warnings seen in tests

- CHANGELOG.md
- src/allotropy/parsers/agilent_gen5/agilent_gen5_parser.py
- src/allotropy/parsers/agilent_gen5_image/agilent_gen5_image_parser.py
- src/allotropy/parsers/agilent_tapestation_analysis/agilent_tapestation_analysis_parser.py
- src/allotropy/parsers/appbio_absolute_q/appbio_absolute_q_parser.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_parser.py
- src/allotropy/parsers/beckman_pharmspec/beckman_pharmspec_parser.py
- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_parser.py
- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_parser.py
- src/allotropy/parsers/biorad_bioplex_manager/biorad_bioplex_manager_parser.py
- src/allotropy/parsers/chemometec_nucleoview/nucleoview_parser.py
- src/allotropy/parsers/ctl_immunospot/ctl_immunospot_parser.py
- src/allotropy/parsers/luminex_xponent/luminex_xponent_parser.py
- src/allotropy/parsers/mabtech_apex/mabtech_apex_parser.py
- src/allotropy/parsers/methodical_mind/methodical_mind_parser.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_parser.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_parser.py
- src/allotropy/parsers/qiacuity_dpcr/qiacuity_dpcr_parser.py
- src/allotropy/parsers/revvity_kaleido/kaleido_parser.py
- src/allotropy/parsers/thermo_fisher_nanodrop_eight/nanodrop_eight_parser.py
- src/allotropy/parsers/unchained_labs_lunatic/unchained_labs_lunatic_parser.py
- src/allotropy/parsers/vendor_parser.py
- src/allotropy/testing/utils.py
- tests/parsers/agilent_gen5/to_allotrope_test.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/beckman_vi_cell_blu/vi_cell_blu_data.py
- tests/parsers/methodical_mind/methodical_mind_parser_test.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_data.py
- tests/to_allotrope_test.py
Update ASM converter name field to specify the parser name instead of just "allotropy", this is intended to give better granularity on the adapter that did the conversion and not just the library version
> feat: Make all adapters have the asm converter name

- src/allotropy/parsers/mabtech_apex/mabtech_apex_contents.py
- src/allotropy/parsers/mabtech_apex/mabtech_apex_parser.py
Tiny refactor - the reasoning here is to enforce a pattern that raw data handling (and as a proxy - pandas imports) do not happen in the parser class.
> refactor: Move pandas read_excel to mabtech contents

- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_contents.py
- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_parser.py
- src/allotropy/parsers/beckman_pharmspec/beckman_pharmspec_parser.py
- src/allotropy/parsers/mabtech_apex/mabtech_apex_contents.py
- src/allotropy/parsers/mabtech_apex/mabtech_apex_parser.py
The goal here is to ban pandas from parser classes, to encourage authors to structure data when reading it.
These are not cases of that, but just other minor uses of pandas that muddy up the results.
> refactor: Remove pandas from parsers simple cases

- src/allotropy/allotrope/schema_mappers/adm/pcr/BENCHLING/_2023/_09/dpcr.py
- src/allotropy/allotrope/schema_mappers/adm/plate_reader/benchling/_2023/_09/plate_reader.py
- src/allotropy/allotrope/schema_mappers/adm/spectrophotometry/benchling/_2023/_12/spectrophotometry.py
- src/allotropy/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure.py
- tests/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure_test.py
This removes a mistaken approach of pulling all calculated documents from all measurement documents into the global calculated data documents list. This is wrong because some ASM documents report calculated data documents inside of measurement documents.
The location of the calculated data documents within the data classes should signal where they should be placed within the ASM document.
This was done in the `plate reader` mapper because one parser (unchained labs) was taking this approach, of putting all calculated data documents in the global document, even if they correspond to measurement rows. I'm not sure why we are putting measurement-specific calculated data documents in the global calculated data document, and I'm not changing it here (left a TODO comment to investigate). …
> refactor: Remove converting measurement calc docs to global calc docs

- .vscode/cspell.json
- .vscode/cspell_companies.txt
- CHANGELOG.md
- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_reader.py
- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_structure.py
The `pivot` operation in XR text file reader can have a failure if there is duplicated data, which was seen a couple times in real life usage. 
Simplify the parsing of the text file into pandas dataframe, removing the need for the pivot entirely.
> fix: Simplify Vi-cell XR text reader

- CHANGELOG.md
- src/allotropy/parsers/roche_cedex_bioht/constants.py
- src/allotropy/parsers/roche_cedex_bioht/roche_cedex_bioht_parser.py
- src/allotropy/parsers/roche_cedex_bioht/roche_cedex_bioht_structure.py
- tests/parsers/roche_cedex_bioht/roche_cedex_bioht_data.py
- tests/parsers/roche_cedex_bioht/roche_cedex_bioht_structure_test.py
- tests/parsers/roche_cedex_bioht/testdata/roche_cedex_bioht_example01.json
- tests/parsers/roche_cedex_bioht/testdata/roche_cedex_bioht_example02.json
- tests/parsers/roche_cedex_bioht/testdata/roche_cedex_bioht_example03.json
- tests/parsers/roche_cedex_bioht/testdata/roche_cedex_bioht_example04.json
- tests/parsers/roche_cedex_bioht/to_allotrope_test.py
This fixes a rare(ish?) edge case in bioht where two measurements for the same sample and property are taken over several days.
In the result files for this parser, all measurements are taken at separate times, but we want to group measurements for a given sample. To do this, all measurements for a sample were group, and then duplicate measurements were aggregated in a list and split out in to separate measurement documents in the order the were encountered.
However, this misses the context of what these duplicate measurements actually are. In reality, a duplicate measurement for a sample happens when multiple measurements are taken over a period of time (in the example file we have, over 3 days). 
To really capture this context, we instead group measurements close in time (using a …
> fix: Fix measurement grouping in roche cedex bioht

- src/allotropy/parsers/utils/timestamp_parser.py
- src/allotropy/parsers/vendor_parser.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_parser_test.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/beckman_pharmspec/beckman_pharmspec_parser_test.py
- tests/parsers/beckman_vi_cell_blu/vi_cell_blu_parser_test.py
- tests/parsers/novabio_flex2/novabio_flex2_structure_test.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_parser_test.py
- tests/parsers/roche_cedex_bioht/roche_cedex_bioht_parser_test.py
- tests/parsers/roche_cedex_bioht/roche_cedex_bioht_structure_test.py
- tests/parsers/utils/timestamp_parser_test.py
Also removes asserts that are impossible due to typing and removes _get_date_time_from_timestamp which is unused.
> refactor: Allow timestamp parser to be None

- src/allotropy/allotrope/schemas/adm/spectrophotometry/BENCHLING/2023/12/spectrophotometry.schema.json
This was missing from this BENCHLING implementation of the spectro schema.
The result of this was that when validating, the schema validation would try to retrieve the schemas for `core.schema` objects from the web, which can fail unit tests if the `purl` addresses are not available at a given time.
This was noticed by one such occurrence of the urls being unavailable. Adding this schema to the defs fixes it.
NOTE: the model classes do not change because these core values are imported from the shared models during instantiation.
> chore: Add missing core schema to spectro schema

- src/allotropy/allotrope/schema_parser/backup_manager.py
Currently, if a user interrupts scripts or tests, a backup file may be left behind. 
Catch keyboard interrupts so this doesn't happen anymore.
> chore: Catch keyboard interrupt in backup_manager

- CONTRIBUTING.md
- tests/parser_factory_test.py
This test doesn't add much value and adds another touchpoint for a new parser.
The idea was to prevent someone from adding a parser and then forgetting to mark it as ready to use.
However, at this time, deciding a parser is ready is largely done by repo owners, who know the drill
> test: Remove non-ready parsers test

- src/allotropy/allotrope/schema_mappers/adm/plate_reader/benchling/_2023/_09/plate_reader.py
- src/allotropy/parsers/agilent_gen5/agilent_gen5_structure.py
- src/allotropy/parsers/agilent_gen5_image/agilent_gen5_image_structure.py
- src/allotropy/parsers/ctl_immunospot/constants.py
- src/allotropy/parsers/ctl_immunospot/ctl_immunospot_structure.py
- src/allotropy/parsers/example_weyland_yutani/constants.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_structure.py
- src/allotropy/parsers/mabtech_apex/constants.py
- src/allotropy/parsers/mabtech_apex/mabtech_apex_structure.py
- src/allotropy/parsers/unchained_labs_lunatic/constants.py
- src/allotropy/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure.py
Because `detection_type` can be different for different measurements in a document, move detection_type to Measurement
> refactor: Move detection_type to Measurement

- CHANGELOG.md
- src/allotropy/parsers/utils/values.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example01.txt
- tests/parsers/utils/values_test.py
We saw an error in an input file that specified an int index with a decimal prefix (1.0 instead of 1).
Make try_int handle this case safely, so we can parse this messy data.
> fix: Allow try_int to handle decimal in int value

- CHANGELOG.md
- pyproject.toml
- scripts/generate_weyland_yutani.py
- scripts/update_version.py
- src/allotropy/parsers/utils/timestamp_parser.py
pytz can create odd timezones if not used correctly (and it's easy to misuse) - use dateutil timezones instead.
> fix: Update timezone parsing to use dateutil timezones instead of pytz

- CHANGELOG.md
- src/allotropy/parsers/roche_cedex_hires/roche_cedex_hires_reader.py
- src/allotropy/parsers/thermo_fisher_qubit4/thermo_fisher_qubit4_reader.py
- src/allotropy/parsers/thermo_fisher_qubit_flex/thermo_fisher_qubit_flex_reader.py
This bug slipped in because unit tests pass BufferedReader, but this only breaks when we pass a BytesIO
TODO is to fix testing coverage, but this fixes the issue.
> fix: Fix call to read_excel in 3 parsers

- CODEOWNERS
Current CODEOWNERS had an issue in that Alejandro and Sebastian could not approve PRs that changed CHANGELOG (or other root level files)
Instead, give them access to all, and then remove access to specific places (the empty ownership removes all owners, then at the end of the file Benchling Connect is given back access)
> chore: Fix codeowners

- CHANGELOG.md
- src/allotropy/parsers/agilent_gen5/agilent_gen5_structure.py
- tests/parsers/agilent_gen5/testdata/luminescence/endpoint_singleplate_without_bandwidth.json
- tests/parsers/agilent_gen5/testdata/luminescence/endpoint_singleplate_without_bandwidth.txt
Fixes a bug seen in Aglient Gen5 where a single wavelength label was read from pandas as a float, but treated as a string.
> fix: Cast data label to str when it may be numeric

- docs/tutorial.md
- tests/conftest.py
- tests/to_allotrope_test.py
Replace test class variables (OVERWRITE_ON_FAILURE) with pytest flags, so users can now run:
`hatch run test --overwrite` to overwrite failing test cases
`hatch run test --filter <regex>` to filter to specific tests to run
`hatch run test --exclude <regex>` to skip specific tests
The makes it easier to test during development, and removes the change to accidentally commit the old class variables to a test.
> test: Add pytest flags for overwrite/filtering tests

- pyproject.toml
jsonschema 4.18.0 introduces a serious performance regression, seemingly due to use of new referencing library: https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4180
While we wait for resolution, pin package below this change.
Current test timing drops from ~3m (with 12 cores parallelized tests) to ~35 sec
For Softmax pro tests (particularly large schema) single threaded tests drop from ~3m to ~6s
> chore: Pin jsonschema below 4.18.0

- CHANGELOG.md
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_absorbance_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example02.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example03.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example04.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_luminescence_example01.json
This makes well identifiers inconsistent with other plate reader documents and standard practice.
The leading zero was only added to make sorting work in particular place in the code, updated the sorting to work without needing leading zero.
> fix: Remove leading '0' from well identifiers in Perkin Elmer Envision

- src/allotropy/parsers/utils/pandas.py
- tests/parsers/utils/pandas_test.py
Having `DataSeries.get` use `try_float_or_none` allows it to handle all edge cases handled by `try_float`, e.g. parsing floats with comma decimals.
> fix: Update DataSeries to use float parsing utility when reading a float value, in order to better handle edge cases

- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
This error was reported in a sentry issue with only the traceback indicanting that a `ValueError` was raised.
Since there are no steps to reproduce but just the traceback I was unable to figure out the format in the `Group` data block that could result in this error, so no additional testing was added for this.
> fix: SoftMax Pro - raise error for unsupported Group data format

- src/allotropy/allotrope/schema_mappers/adm/spectrophotometry/benchling/_2023/_12/spectrophotometry.py
- src/allotropy/parsers/thermo_fisher_qubit_flex/thermo_fisher_qubit_flex_structure.py
- tests/parsers/thermo_fisher_qubit_flex/testdata/thermo_fisher_qubit_flex_example_01.json
Add back software version, rename "selected standards" back to "selected samples", accidentally deleted here: https://github.com/Benchling-Open-Source/allotropy/pull/699/files
> fix: ThermoFisher Qubit Flex - add fields that were accidentally removed/renamed in refactor

- pyproject.toml
pypi seems to have stopped supporting the other way
> chore: Update to use license classifier instead of field

- src/allotropy/parsers/chemometec_nucleoview/nucleoview_structure.py
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example07.csv
- tests/parsers/chemometec_nucleoview/testdata/chemometec_nucleoview_example07.json
- Updated adapter to handle missing viable cell density
> feat: ChemoMetec NucleoView - Incorporate error document when viable cell density is missing

- src/allotropy/allotrope/schema_mappers/adm/pcr/rec/_2024/_09/qpcr.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_data_creator.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example05.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example06.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example07.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example08.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_minimal_broken_path_calc_doc.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_minimal_test02.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_minimal_test04.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_minimal_test07.json
The migration to REC/2024/09 dropped two important pieces of metadata, reference DNA description and reference sample description. Add them back as custom info, since they are not in the REC schema.
> feat: AppBio QuantStudio RT-PCR - add back reference fields as custom data processing info

- src/allotropy/parsers/unchained_labs_lunatic/constants.py
- src/allotropy/parsers/unchained_labs_lunatic/unchained_labs_lunatic_reader.py
- src/allotropy/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure.py
- tests/parsers/unchained_labs_lunatic/testdata/2024-07-12_CW288_Plate1.json
- tests/parsers/unchained_labs_lunatic/testdata/2024-07-16_CW288_Plate2.json
- tests/parsers/unchained_labs_lunatic/testdata/Demo_A260_dsDNA_Data.json
- tests/parsers/unchained_labs_lunatic/testdata/Demo_A280_Protein.csv
- tests/parsers/unchained_labs_lunatic/testdata/Demo_A280_Protein.json
- tests/parsers/unchained_labs_lunatic/testdata/Example_Lunatic_Plate_Reader_csv_no_header.json
- tests/parsers/unchained_labs_lunatic/testdata/Example_Lunatic_Plate_Reader_csv_with_header.json
- tests/parsers/unchained_labs_lunatic/testdata/Example_Lunatic_Plate_Reader_xlsx_no_header.json
- tests/parsers/unchained_labs_lunatic/testdata/Example_Lunatic_Plate_Reader_xlsx_with_header.json
- tests/parsers/unchained_labs_lunatic/testdata/spectrum_measurement.json
- tests/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure_test.py
We've seen recent failures in Unchained Labs parser because column names can have different case (e.g. "Sample Name" vs "Sample name")
To fix this, force everything to lowercase.
> fix: Unchained Labs Lunatic - handle different cases for column headers

- .github/workflows/test.yml
ubuntu-20.44 is being deprecated, recommended to use ubuntu-latest 
https://github.com/actions/runner-images/issues/11101
> chore: Update github workflow to use ubuntu-latest

- src/allotropy/parsers/beckman_echo_plate_reformat/beckman_echo_plate_reformat_structure.py
- tests/parsers/beckman_echo_plate_reformat/testdata/ExceptionsOnly.json
- tests/parsers/beckman_echo_plate_reformat/testdata/PartialTransfer.json
- tests/parsers/beckman_echo_plate_reformat/testdata/SurveyVolumeExamples.csv
- tests/parsers/beckman_echo_plate_reformat/testdata/SurveyVolumeExamples.json
- tests/parsers/beckman_echo_plate_reformat/testdata/TransferOnly.json
Survey volume results (for 'Survey Fluid Volume' and 'Current Fluid Volume' fields in the Echo output CSV) are already in microliters, and we were spuriously converting this number "from nl to ul" resulting in incorrect volumes in the output data.  
Also added another test case that has exceptions with valid survey results.
> fix: Beckman Echo Plate Reformat -  remove accidental volume conversion of survey volume results

- src/allotropy/parsers/beckman_echo_plate_reformat/beckman_echo_plate_reformat_structure.py
- tests/parsers/beckman_echo_plate_reformat/testdata/SurveyVolumeExamples.json
One example file has the per-measurement time missing a date (it provides time only).
In this case, the default behavior of the dateutil library is to use today's date, which is incorrect.
Instead, fill the date with the file header's date, is possible.
If the measurement time is missing a date, and the header has no date, throw an error.
> fix: Beckman Echo Plate Reformat - update measurement time to fill missing date with file date if needed

- src/allotropy/parsers/agilent_openlab_cds/agilent_openlab_cds_decoder.py
- src/allotropy/parsers/agilent_openlab_cds/agilent_openlab_cds_parser.py
Allotropy parsers must read from bytes, not from local files, as the interface allows passing in bytes.
> fix: Agilent OpenLab CDS - use bytes to read zip file instead of file name
