Benchling-Open-Source/allotropy

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_builders.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
- Decouple calculated document builder in AppBio QuantStudio
> refac: decouple calculated document builder in quantstudio

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/appbio_quantstudio/calculated_document.py
- Redefine calculated data documents references as required in AppBio QuantStudio
> fix: redefine calculated data documents references as required

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/decorators.py
- Fix recalculation of function when result is null in cache of AppBio Quantstudio
> fix: bug in cache AppBio Quantstudio

- pyproject.toml
Added contributing authors to toml
> Chore: Update pyproject.toml with authors

- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example01_v2.json
This new JSON file is what the updated parser should match.
> chore: Add new target JSON for PE_Envision_fluorescence_example01.csv

- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
Test existing behavior before improving it.
> Add test_create_basic_assay_info_fails()

- GOVERNANCE.md
Please review (and let me know whether Nathan or Joe should be BDFL - I picked Nathan because he's been the largest contributor to date).
> Governance model

- CHANGELOG.md
- src/allotropy/parsers/lines_reader.py
- Allow lines reader to accept or infer encoding
> feat: Allow lines reader to accept or infer encoding

- README.md
After this PR (https://github.com/Benchling-Open-Source/allotropy/pull/44) we need to also change the name in the README.
> Update README with rename from 'fix' to 'fmt'

- pyproject.toml
Ensure that any further Python files added to `/scripts` get checked by mypy.
> Enable mypy for scripts directory

- pyproject.toml
- tests/parsers/beckman_vi_cell_blu/vi_cell_blu_parser_test.py
Extract constants and helpers, use more_itertools.one(), etc.
> Improve vi_cell_blu_parser_test

- .idea/misc.xml
IntelliJ config files should end without a newline as that's how they're generated. Also add black auto-formatting.
> Fix .idea/misc.xml

- CONTRIBUTING.md
- README.md
Adds some clarifications for hatch and GPG signing to resolve some commonly-seen issues.
> Update README and CONTRIBUTING with hatch and GPG signing notes

- CHANGELOG.md
- src/allotropy/parsers/lines_reader.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
> Simplify lines reader

- src/allotropy/parsers/vendor_parser.py
Remove unused code, order methods, etc.
> Clean up VendorParser

- CONTRIBUTING.md
- src/allotropy/exceptions.py
- src/allotropy/parsers/agilent_gen5/agilent_gen5_parser.py
- src/allotropy/parsers/agilent_gen5/plate_data.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
- src/allotropy/parsers/novabio_flex2/novabio_flex2_structure.py
- tests/parsers/moldev_softmax_pro/to_allotrope_test.py
With some recent error messaging changes, add a helper function and contributing guidelines to promote uniform error messaging across the repo.
> Clean up error messaging and add to contributing guidelines

- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- simplify Perkin Elmer Envision adapter
> refac: simplify Perkin Elmer Envision adapter

- tests/allotrope/schema_parser/model_class_editor_test.py
> Freeze dataclasses in tests

- src/allotropy/parsers/agilent_gen5/agilent_gen5_structure.py
- src/allotropy/parsers/agilent_gen5/plate_data.py
- src/allotropy/parsers/appbio_absolute_q/constants.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
- src/allotropy/parsers/appbio_quantstudio/calculated_document.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_structure.py
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
- src/allotropy/parsers/novabio_flex2/novabio_flex2_structure.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
- src/allotropy/parsers/roche_cedex_bioht/roche_cedex_bioht_structure.py
Immutability is good.
Done via mass find-and-replace, then rolling back where lint/tests failed.
> Freeze most dataclasses in parsers

- src/allotropy/parsers/agilent_gen5/agilent_gen5_parser.py
- src/allotropy/parsers/appbio_absolute_q/appbio_absolute_q_parser.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_parser.py
- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_parser.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_parser.py
- src/allotropy/parsers/novabio_flex2/novabio_flex2_parser.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_parser.py
- src/allotropy/parsers/roche_cedex_bioht/roche_cedex_bioht_parser.py
- src/allotropy/parsers/vendor_parser.py
Protect a method that's not part of the public contract.
> Protect VendorParser.get_date_time()

- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
It's unfortunate that this wasn't caught by lint.
> Fix error path in PlateBlock.create()

- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
Put the simpler case first and eliminate a lot of indenting.
Out of scope: breaking up a very long method.
> Reduce indentation in PlateBlock.create()

- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/novabio_flex2/novabio_flex2_structure_test.py
- tests/parsers/roche_cedex_bioht/roche_cedex_bioht_structure_test.py
- tests/parsers/unchained_labs_lunatic/unchained_labs_lunatic_structure_test.py
Make it clearer where the error should occur.
> Reduce code in "with pytest.raises" blocks

- src/allotropy/exceptions.py
- src/allotropy/parsers/novabio_flex2/novabio_flex2_structure.py
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_parser.py
- tests/exceptions_test.py
- tests/parsers/novabio_flex2/novabio_flex2_structure_test.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_parser_test.py
Require a message and fix two callers.
> Require a message in AllotropeConversionError

- tests/parsers/agilent_gen5/to_allotrope_test.py
- tests/parsers/test_utils.py
Test a previously unused function. (It's used in neither src nor tests.)
> Test allotrope_model_from_file()

- tests/to_allotrope_test.py
> Test invalid file paths in to_allotrope

- src/allotropy/to_allotrope.py
- tests/to_allotrope_test.py
Make `allotrope_from_file` delegate to `allotrope_model_from_file`.
> Use allotrope_model_from_file

- src/allotropy/to_allotrope.py
Slight improvement inspired by #200
> Improve readability in allotrope_from_io()

- src/allotropy/allotrope/models/shared/definitions/units.py
- src/allotropy/allotrope/schemas/shared/definitions/units.json
Adding ng/uL, ug/uL, ng/mL, ug/mL, and mg/mL mass concentration units to units.json.
> Additional mass concentration units for units.json

- tests/parsers/lines_reader_test.py
> Refactor lines_reader_test

- src/allotropy/allotrope/models/shared/definitions/custom.py
- src/allotropy/allotrope/schemas/shared/definitions/custom.json
Addition of modified tQuantityValue for mass concentations: ng/uL, ug/uL, ng/mL, ug/mL, mg/mL
> Additional mass concentration tQuantityValue for custom.json

- src/allotropy/allotrope/models/shared/definitions/custom.py
- src/allotropy/allotrope/schemas/shared/definitions/custom.json
Addition of tQuantityValueSquareCentimetersPerGram to custom.json to support user in `spectrophotometry` schema
> Addition of tQuantityValueSquareCentimetersPerGram to custom.json

- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
> Freeze SoftMaxPro dataclasses

- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_parser.py
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example01.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example02.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example04.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example05.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_luminescence_endpoint_example03.json
- tests/parsers/moldev_softmax_pro/testdata/abs_endpoint_plates.json
- fix moldev softmax pro manifest specification
> fix: moldev softmax pro manifest specification

- CHANGELOG.md
- src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_parser.py
- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_data.py
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_absorbance_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example01.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example04.json
- tests/parsers/perkin_elmer_envision/testdata/PE_Envision_luminescence_example01.json
> Use UNITLESS in Elmer Envision -- functional change

- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
Migrate calls missed in 9b6f5845
> More random_uuid_str() migrations

- CHANGELOG.md
- src/allotropy/parsers/moldev_softmax_pro/softmax_pro_parser.py
- Do not add empty list of calculated data documents to Moldev Softmax Pro output
> fix: Do not add empty list of calculated data documents to Moldev Softmax Pro output

- CHANGELOG.md
- src/allotropy/parsers/moldev_softmax_pro/constants.py
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example01.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example02.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example04.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_absorbance_endpoint_example05.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_fluorescence_endpoint_example06.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_fluorescence_endpoint_example07.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_luminescence_endpoint_example03.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_luminescence_endpoint_example08.json
- tests/parsers/moldev_softmax_pro/testdata/MD_SMP_luminescence_endpoint_example09.json
- tests/parsers/moldev_softmax_pro/testdata/abs_endpoint_plates.json
-  Replace null with N/A in Moldev Softmax Pro
> feat: Replace null with N/A in Moldev Softmax Pro

- src/allotropy/parsers/thermo_fisher_nanodrop_eight/nanodrop_eight_parser.py
> Use random_uuid_str() in nanodrop_eight_parser

- tests/parsers/agilent_gen5/to_allotrope_test.py
Make this a better unit test by testing (part of) the in-memory `Model`. The exact serialization of the `Model` is tested in `test_to_allotrope_absorbance()`.
Note that this is the only unit test for `allotrope_model_from_file`. It is called in src by `allotrope_from_file`, which has lots of unit tests.
> Test Model in test_model_from_file_absorbance()

- docs/tutorial.md
- pyproject.toml
- scripts/csv_as_json.py
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_simple_correct.json
Also mention the ability to update test files with the test function
> fix: Update the Wayland-Yutani tutorial to use hatch for running the script

- tests/parsers/perkin_elmer_envision/perkin_elmer_envision_structure_test.py
> Fix TODO in test_create_basic_assay_info_fails

- CHANGELOG.md
- pyproject.toml
- src/allotropy/allotrope/allotrope.py
Increase package compatibility
> chore: Loosen requirements on jsonschema

- CHANGELOG.md
- src/allotropy/parsers/unchained_labs_lunatic/constants.py
- Add missing case for concentration column without A260 prefix in Unchained Labs Lunatic
> Add missing case for concentration column without A260 prefix in Unchained Labs Lunatic

- CHANGELOG.md
- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_parser.py
- src/allotropy/parsers/beckman_vi_cell_blu/vi_cell_blu_reader.py
- Add encoding inference to Beckman Vi Cell Blu adapter
> add encoding inference to Beckman Vi Cell Blu adapter

- src/allotropy/parsers/appbio_quantstudio/README.md
- Add readme for Appbio Quantstudio adapter
> add readme for Appbio Quantstudio adapter

- CHANGELOG.md
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_calculated_documents.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_data_creator.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_parser.py
- src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_data.py
- tests/parsers/appbio_quantstudio/appbio_quantstudio_structure_test.py
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example04.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_example07.json
- tests/parsers/appbio_quantstudio/testdata/appbio_quantstudio_multiple_cal_doc_wells.json
- rm inner calculated data documents from AppBio Quantstudio structure
- Update test files
> rm inner calculated data documents from AppBio Quantstudio structure

- scripts/visualization.py
fix bad argument name in visualization script
> fix bad argument name in visualization script

- src/allotropy/parsers/methodical_mind/methodical_mind_structure.py
- tests/parsers/methodical_mind/methodical_mind_structure_test.py
This is the signed version of: https://github.com/Benchling-Open-Source/allotropy/pull/414/files
> update methodical mind structure to account for blank user

- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_parser.py
- src/allotropy/parsers/example_weyland_yutani/example_weyland_yutani_structure.py
- tests/parsers/example_weyland_yutani/testdata/Weyland_Yutani_example01.json
- Example parser now extracts the processed data values from the csv
- Fixed the layout of cell_data by transposing the data frame
- Added support for extracting the instrument spec
> feat: add support for extracting processed data values and instrument spec

- src/allotropy/allotrope/schema_parser/generate_schemas.py
> chore: Suppress schema generation warnings

- pyproject.toml
> chore: Add Joshua to authors

- CHANGELOG.md
- pyproject.toml
This fixes https://github.com/pydantic/pydantic/issues/9637 for schema generator
> fix: Upgrade pydantic

- .github/workflows/test.yml
- pyproject.toml
Reduces unit test time on my computer (12 core) from `~3m` -> `~1.25m`
> test: Parallelize tests

- src/allotropy/parsers/agilent_gen5/agilent_gen5_parser.py
This is causing compatibility issues with benchling
> chore: Remove switch statement

- CHANGELOG.md
- pyproject.toml
> chore: update pandas from 2.1 to 2.2

- src/allotropy/parsers/beckman_vi_cell_xr/vi_cell_xr_reader.py
Found an error reading a file where a number header was interpreted as a float, this fixes to coerce to string
> chore: Fix string on join

- pyproject.toml
- tests/to_allotrope_test.py
Exclude tests from coverage report, and generate XML coverage report that can be used by vscode plugin
> test: Improve code coverage settings and generate XML report

- src/allotropy/parsers/methodical_mind/methodical_mind_structure.py
- tests/parsers/methodical_mind/testdata/methodical_test_1.json
- tests/parsers/methodical_mind/testdata/methodical_test_2.json
Reverted Unc Path to be the instrument file instead of NA
> feat: Update Methodical Mind adapter to use REC schema

- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_calculated_documents.py
Fix typo mistake in https://github.com/Benchling-Open-Source/allotropy/pull/704
> chore: Fix typo from refactor PR 704

- scripts/update_version.py
The update-verison script will now:
1. Create a new branch
2. Tag the version commit
3. Create a Github release
> chore: Update release script to tag version and create a Github release

- src/allotropy/parsers/cytiva_unicorn/structure/metadata.py
- src/allotropy/parsers/cytiva_unicorn/structure/static_docs.py
- tests/parsers/cytiva_unicorn/testdata/unicorn_1.json
- Multiply inner column diameter by 10
- Redefine analyst as first non system value of operator in EvaluationLog.xml
> feat: Cytiva Unicorn - Update inner column diameter and analyst fields

- src/allotropy/allotrope/schema_mappers/adm/liquid_chromatography/benchling/_2023/_09/liquid_chromatography.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/absorbance.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/concentration.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/conductivity.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/flow.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/ph.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/pressure.py
- src/allotropy/parsers/cytiva_unicorn/structure/measurements/temperature.py
- src/allotropy/parsers/cytiva_unicorn/structure/static_docs.py
- tests/parsers/cytiva_unicorn/testdata/unicorn_1.json
- add start time setting to liquid chromatography benchling 09/23 mapper
- add start time setting to device control document in unicorn adapter
> feat: Cytiva Unicorn - add start time to device control doc

- src/allotropy/calcdocs/appbio_quantstudio_designandanalysis/config.py
- src/allotropy/calcdocs/appbio_quantstudio_designandanalysis/extractor.py
- src/allotropy/calcdocs/config.py
- src/allotropy/calcdocs/extractor.py
- redefine extractor element as referenceable in calcdocs
- include actual values in calcdocs data sources
> feat: complete missing values in Calcdocs

- src/allotropy/calcdocs/config.py
- src/allotropy/parsers/utils/calculated_data_documents/definition.py
- add unit and description attributes to calcdocs
> feat: add unit and description attributes to calcdocs

- src/allotropy/parsers/appbio_quantstudio_designandanalysis/appbio_quantstudio_designandanalysis_data_creator.py
- src/allotropy/parsers/appbio_quantstudio_designandanalysis/structure/generic/structure.py
- tests/parsers/appbio_quantstudio_designandanalysis/testdata/appbio_quantstudio_design_quantity_test.json
- add custom logic to store quantity values in custom information document when the calculated data document is not created
- update expected test output
> feat: Appbio Quantstudio design and analysis - store quantity as custom info when calcdata ignores value
